version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    container_name: uniquote_postgres
    environment:
      POSTGRES_USER: uniquote_user
      POSTGRES_PASSWORD: 123456     
      POSTGRES_DB: uniquote_db
      PGUSER: postgres
      POSTGRES_HOST_AUTH_METHOD: md5  
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
